In [1]:
from utils import prepare_jupyter
prepare_jupyter()

In [30]:
import numpy as np
import lightgbm as lgb

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris, load_breast_cancer
from sklearn.metrics import accuracy_score
from data import Dataset
from structure import AdaboostEnsemble, RandomForestEnsemble, LGBEnsemble
from predict import majority_voting

In [31]:
# Data
iris_train, iris_val = Dataset.from_sklearn('iris', load_iris()).split()
cancer_train, cancer_val = Dataset.from_sklearn('cancer', load_breast_cancer()).split()

train_data, val_data = iris_train, iris_val
# train_data, val_data = cancer_train, cancer_val

## Sklearn

In [34]:
# Somehow it works for max_depth >=7, and not <7
params = {
    'max_depth': 2,
    'n_estimators': 4
}

ensemble = AdaboostEnsemble(params)
ensemble.fit(train_data)

ensemble_preds = ensemble.predict(val_data.X)
clf_preds = ensemble.clf_predict(val_data.X)
print(clf_preds)

accuracy_score(clf_preds, ensemble_preds)

[2 2 1 1 0 1 0 0 0 2 1 0 1 0 1]


0.8666666666666667

In [35]:
ensemble = RandomForestEnsemble(params)
ensemble.fit(train_data)

ensemble_preds = ensemble.predict(val_data.X)
clf_preds = ensemble.clf_predict(val_data.X)
print(clf_preds)

accuracy_score(clf_preds, ensemble_preds)

[2 2 2 2 0 1 0 0 0 2 2 0 2 0 1]


0.8666666666666667

## Light GBM

In [25]:
ensemble = LGBEnsemble(params)
ensemble.fit(train_data)

clf_preds = ensemble.clf.predict(val_data.X)
preds = ensemble.predict(val_data.X)

print(clf_preds)
print(preds)
print(accuracy_score(val_data.y, preds))
print(accuracy_score(val_data.y, clf_preds))
print(f'Node div = {ensemble.node_diversity()}')

[1 2 1 2 2 1 2 1 1 2 0 0 0 1 0]
[1 2 1 2 2 1 2 1 1 2 0 0 0 1 0]
1.0
1.0
Node div = 1.1055415967851332
